apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-provisioner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-provisioner
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-provisioner
  template:
    metadata:
      labels:
        app: nfs-provisioner
    spec:
      serviceAccountName: nfs-provisioner
      containers:
      - name: nfs-provisioner
        image: quay.io/external_storage/nfs-client-provisioner:latest
        volumeMounts:
        - name: nfsstor
          mountPath: /persistentvolumes
        env:
        - name: PROVISIONER_NAME
          value: nfs.com/fs
        - name: NFS_SERVER
          value: 192.168.0.100
        - name: NFS_PATH  
          value: /nfsstor
      volumes:
      - name: nfsstor
        nfs:
          server: 192.168.0.100
          path: /nfsstor