apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
 name: cephrbd-storageclass
provisioner: ceph.com/rbd
parameters:
 monitors: 192.168.0.100:6789
 adminId: admin
 adminSecretName: cephrbd-dynamic-admin-secret
 pool: cephpool
 userId: kube
 userSecretName: cephrbd-dynamic-kube-secret
 fsType: ext4
 imageFormat: "2"
 imageFeatures: "layering"