apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
  - name: secret-env-pod
    image: busybox
    args:
    - /bin/sh
    - -c
    - sleep 3000
    env:
    - name: SECRET_USERNAME
      valueFrom:
        secretKeyRef:
          name: secret
          key: username
    - name: SECRET_PASSWORD
      valueFrom:
        secretKeyRef:
          name: secret
          key: password