apiVersion: v1
kind: PersistentVolume
metadata:
  name: cephfs-static-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: cephfs
  cephfs:
    monitors:
    - 192.168.0.100:6789 
    user: admin 
    path: /
    secretRef:
      name: cephfs-static-secret