apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-static-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: cephfs