apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-hpa
spec:
  replicas: 2
  selector:
    matchLabels:
      run: deploy-hpa
  template:
    metadata:
      labels:
        run: deploy-hpa
    spec:
      containers:
      - image: nginx
        name: deploy-hpa
        resources:
          limits:
            cpu: 50m