apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange
spec:
  limits:
  - default:
      memory: 512Mi
      cpu: 2
    defaultRequest:
      memory: 256Mi
      cpu: 0.5
    max:
      memory: 800Mi
      cpu: 3
    min:
      memory: 100Mi
      cpu: 0.3
    maxLimitRequestRatio:
      memory: 2
      cpu: 2
    type: Container