apiVersion: v1
kind: Pod
metadata:
  name: resources-qos-besteffort
spec:
  containers:
  - name: resources-qos-besteffort
    image: polinux/stress
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "50M", "--vm-hang", "1"]

---
apiVersion: v1
kind: Pod
metadata:
  name: resources-qos-burstable
spec:
  containers:
  - name: resources-qos-burstable
    image: polinux/stress
    resources:
      requests:
        cpu: 1
        memory: 200Mi
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "50M", "--vm-hang", "1"]

---
apiVersion: v1
kind: Pod
metadata:
  name: resources-qos-guaranteed
spec:
  containers:
  - name: resources-qos-guaranteed
    image: polinux/stress
    resources:
      requests:
        cpu: 1
        memory: 200Mi
      limits:
        cpu: 1
        memory: 200Mi
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "50M", "--vm-hang", "1"]