apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    run: statefulset
  name: statefulset
spec:
  serviceName: service
  replicas: 6
  selector:
    matchLabels:
      run: statefulset
  template:
    metadata:
      labels:
        run: statefulset
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: statefulset
        image: nginx:1.18
        ports:
        - containerPort: 80
          name: port
        volumeMounts:
        - name: pvc
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: pvc
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: nfs