apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rbd-provisioner
subjects:
- kind: ServiceAccount
  name: rbd-provisioner
roleRef:
  kind: Role
  name: rbd-provisioner
  apiGroup: rbac.authorization.k8s.io