apiVersion: apps/v1
kind: Deployment
metadata:
  name: cephfs-provisioner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cephfs-provisioner
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cephfs-provisioner
    spec:
      serviceAccount: cephfs-provisioner
      containers:
      - name: cephfs-provisioner
        image: quay.io/external_storage/cephfs-provisioner:latest
        env:
        - name: PROVISIONER_NAME
          value: ceph.com/cephfs
        command:
        - "/usr/local/bin/cephfs-provisioner"
        args:
        - "-id=cephfs-provisioner-1"
        - "-disable-ceph-namespace-isolation=true"