apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cephfs-provisioner
subjects:
- kind: ServiceAccount
  name: cephfs-provisioner
roleRef:
  kind: Role
  name: cephfs-provisioner
  apiGroup: rbac.authorization.k8s.io