apiVersion: v1
kind: Pod
metadata:
  name: configmap-vloume-1-pod
spec:
  containers:
  - name: configmap-vloume-1-pod
    image: busybox
    args:
    - /bin/sh
    - -c
    - sleep 3000
    volumeMounts:
    - name: foo
      mountPath: /etc/foo
      readOnly: true
  volumes:
  - name: foo
    configMap:
      name: configmap