apiVersion: v1
kind: Pod
metadata:
  name: healthcheck-liveness
spec:
  restartPolicy: OnFailure
  containers:
  - name: healthcheck-liveness
    image: busybox
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 3000
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 10
      periodSeconds: 5