apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonset
  labels:
    run: daemonset
spec:
  selector:
    matchLabels:
      run: daemonset
  template:
    metadata:
      labels:
        run: daemonset
    spec:
      containers:
      - name: daemonset
        image: nginx