apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcheck
spec:
  replicas: 6
  selector:
    matchLabels:
      run: healthcheck
  template:
    metadata:
      labels:
        run: healthcheck
    spec:
      containers:
      - name: healthcheck
        image: busybox
        args:
        - /bin/sh
        - -c
        - sleep 3000
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 10
          periodSeconds: 5