apiVersion: v1
kind: Pod
metadata:
  name: nfs-static-pod
spec:
  containers:
  - name: nfs-static-pod
    image: busybox
    args:
    - /bin/sh
    - -c
    - sleep 30000
    volumeMounts:
    - mountPath: /data
      name: data
  volumes:
  - name: data
    persistentVolumeClaim: 
      claimName: nfs-static-pvc