apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: networkpolicy-deny-all-both
spec:
  podSelector:
    matchLabels:
      run: deploy
  policyTypes:
  - Ingress
  - Egress