apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcheck
spec:
  replicas: 6
  selector:
    matchLabels:
      run: healthcheck
  template:
    metadata:
      labels:
        run: healthcheck
    spec:
      containers:
      - name: healthcheck
        image: nginx