apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: glusterfs-storageclass
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://192.168.0.101:8080"
  restauthenabled: "false"
  volumetype: "replicate:3"