apiVersion: v1
kind: PersistentVolume
metadata:
  name: glusterfs-static-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: glusterfs-static-cluster
    path: rep_vol
    readOnly: false