apiVersion: v1
kind: Service
metadata:
  name: service-nodeport
spec:
  ports:
  - name: 8080-80
    port: 8080
    protocol: TCP
    targetPort: 80
    nodePort: 30303
  selector:
    run: deploy
  type: NodePort