apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: job-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate: 
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            command: ["echo", "Hello Kubernetes Job!"]
          restartPolicy: OnFailure