apiVersion: batch/v1
kind: Job
metadata:
  name: job-parallel
spec:
  completions: 6
  parallelism: 2
  template:
    metadata:
      name: job-parallel
    spec:
      containers:
      - name: hello
        image: busybox
        command: ["echo", "Hello Kubernetes Job!"]
      restartPolicy: Never